# Generated by Django 3.1.4 on 2020-12-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('userslug', models.CharField(max_length=50, unique=True)),
                ('aboutperson', models.CharField(blank=True, default='', max_length=500)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('aboutprofile', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('photo', models.ImageField(default='', upload_to='profile/image')),
                ('timeStamp1', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
